apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tetris-multicluster
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-tetris'
    spec:
      project: default
      source:
        repoURL: https://github.com/kiranbabukk/devsecops-Tetris-manifest.git
        targetRevision: HEAD
        path: .
      destination:
        server: '{{server}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
